name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "setup.py"
      - "requirements.txt"

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/torch
            ~/.cache/huggingface
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache model
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface/hub
          key: ${{ runner.os }}-model-qwen-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-model-qwen-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Debug environment
        run: |
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          if [ -f "$GITHUB_EVENT_PATH" ]; then
            echo "Event file exists"
            cat "$GITHUB_EVENT_PATH"
          else
            echo "Event file not found"
          fi

      - name: Run code review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRANSFORMERS_CACHE: ~/.cache/huggingface/hub
          TORCH_HOME: ~/.cache/torch
        run: |
          .github/scripts/code_review.py
